Create 3_premiers_mondes.tex
RaitoBezarius/projet-maths-lean pull request #1
Opened 2020-03-13 13:20 UTC by Maryem-HAJJI

2020-03-13 13:25 UTC, RaitoBezarius reviewed
Ça me paraît bon à vérifier sur le reste

2020-03-13 13:25 UTC, RaitoBezarius commented on 3_premiers_mondes.tex
> +\textbf{4${ème}$ niveau}: L'addition est commutative, c'est à dire pour tout entiers naturels a et b : $$a+b=b+a$$
pour tous

2020-03-13 13:25 UTC, RaitoBezarius commented on 3_premiers_mondes.tex
> +Addition world est le premier monde de \textbf{Natural Number Game}. Dans ce monde, on dispose principalement de 3 tactiques: \textit{refl}, \textit{rw} (dont l'application était initié dans tutorial
met un World majuscule

2020-03-14 19:07 UTC, RaitoBezarius requested changes
Quelques petites choses sur la forme, etc. Mais nickel sinon!

2020-03-14 19:07 UTC, RaitoBezarius commented on 3_premiers_mondes.tex
> + \textbf{rw add\_succ,} : Pour utiliser un des théorèmes qui manipulent le chiffre 0, il faut qu'on introduit la variable $n$ dans $succ()$. On obtient ainsi $succ(n)=succ(n+0)$ \\
Il faut plutôt dire, `add_succ` fournit l'égalité `n + succ(0) = succ(n + 0)` (évidente), on peut l'utiliser pour procéder à la réécriture de la quantité.

2020-03-14 19:07 UTC, RaitoBezarius commented on 3_premiers_mondes.tex
> +\textbf{rw one\_eq\_succ\_zero,} : On remplace 1 par succ(0), puisque c'est plus facile de manipuler le chiffre 0 que le chiffre 1. On obtient donc $succ(n)=n+succ(0)$\\
Plutôt que remplacer, on réécrit (systèmes de réécritures) ; il est aussi important de dire que cela est évidemment possible puisque `1 = succ(0)` (ce qui est tout l'objet du théorème `one_eq_succ_zero`).

2020-03-14 19:07 UTC, RaitoBezarius commented on 3_premiers_mondes.tex
> +\textbf{induction a with d hd,} : Par induction sur a\\
Il faut indiquer (je le ferais peut-être mais répéter ça me paraît bien ici), que `d hd` signifie que l'induction se faisant sur `a`, dans l'induction, `a` est renommé en `d` qui varie inductivement et `hd` est l'hypothèse d'induction sur `d`

2020-03-14 19:07 UTC, RaitoBezarius commented on 3_premiers_mondes.tex
> +\textbf{rw succ\_add,} : on doit se ramener à une équation où l'un des deux cotés est égal à un coté de hd, donc on doit remplacer succ() par des opérations arithmétiques\\
Plutôt qu'on doit, on peut! Ce n'est pas nécessaire de le prouver forcément comme ça

2020-03-14 19:07 UTC, RaitoBezarius commented on 3_premiers_mondes.tex
> +\textbf{rw succ\_add,} : on doit se ramener à une équation où l'un des deux cotés est égal à un coté de hd, donc on doit remplacer succ() par des opérations arithmétiques\\
Ajoute que celui ci est appliqué sur `succ d + b` et nul part ailleurs, puisque c'est la seule instance à laquelle on peut l'appliquer.

2020-03-14 19:07 UTC, RaitoBezarius commented on 3_premiers_mondes.tex
> +pour tout entiers naturels a et b:$$ (a+b)^2=a^2+b^2+2*a*b $$
ajoute un petit clin d'œil genre "retour en troisième" ou Le fameux binôme de Newton

2020-03-14 19:07 UTC, RaitoBezarius commented on src/main.tex
> +    \item \textbf{refl}: Cette tactique prouve toute égalité de la forme A=A. C'est à dire tout égalité dont les deux cotés sont égaux terme à terme. \\
C'est la **reflexivité** de l'égalité!

2020-03-14 19:07 UTC, RaitoBezarius commented on src/main.tex
> +    Soit F l'équation à démontrer.
Soyons un peu rigoureux, prenons un cadre sympathique, suppose que dans tous les textes, on fera l'hypothèse qu'il existe $\Sigma$ un alphabet et donc, $F$ est un mot sur $\Sigma^{*}$.

Lorsque tu fais `rw H,`, tu prends le mot $F$ pour en dériver un mot $F'$ à de la réécriture que l'hypothèse $H$ te fournit (pense grammaire hors contexte si tu veux, mais attention, on a pas des HC ici! y a un langage derrière, mais évitons d'en parler trop.)

Cela donnera une certaine élégance à ton propos.

2020-03-14 19:07 UTC, RaitoBezarius commented on src/main.tex
> +    \hspace{1cm} Soit T une preuve d'un théorème sous la forme d'une égalité (c'est à dire T: A=B), supposé prouvé dans un des niveaux précédent (figure sur le menu des théorèmes). Alors \textbf{rw T
Ce paragraphe est pareil, j'aime mieux la formulation, si on se donne `T: A = B` un type `A = B` (i.e. une preuve de `A = B`), on peut alors l'utiliser pour réécrire dans les mots de A vers B ou de B vers A.

2020-03-14 19:07 UTC, RaitoBezarius commented on src/main.tex
> +    \item \textbf{simp}: C'est une tactique de haut niveau. Elle est disponible à partir du dernier niveau de \textit{Addition world}. Son principe est le suivant; elle utilise la tactique \textbf{rw
À ajouter rapidement que `simp` peut être amélioré et on peut lui apprendre à simplifier plus de choses avec le langage de métaprogrammation de Lean.

2020-03-14 20:37 UTC, Maryem-HAJJI commented on 3_premiers_mondes.tex
> +pour tout entiers naturels a et b:$$ (a+b)^2=a^2+b^2+2*a*b $$
je vois pas trop ce que tu veux dire  par retour en troisième, et pour la formule de binôme de Newton, tu veux dire qu'il faut ajouter qu'il s'agit bien de cette formule là ou bien tu veux que je l'ecrive explicitement dans le théorème (la formule de Newton)?

2020-03-15 00:45 UTC, RaitoBezarius commented on 3_premiers_mondes.tex
> +pour tout entiers naturels a et b:$$ (a+b)^2=a^2+b^2+2*a*b $$
je suis claqué mais tu peux juste dire qu'il s'agit d'une identité remarquable de troisième en France ou alors du cas particulier du binôme de Newton dans le cas n = 2.

2020-03-15 12:04 UTC, RaitoBezarius commented on src/main.tex
> + \textbf{simp,}  \textit{On met les termes à gauche dans le bon ordre } \\
les termes du membre de gauche mais tkt

2020-03-15 13:31 UTC, RaitoBezarius approved these changes
Good

2020-03-15 13:31 UTC, RaitoBezarius commented on src/main.tex
> +    \item On suppose dans cette partie que:\\ - $\Sigma$ est un alphabet fini qui contient les lettres de l'alphabet latin, les parenthèses et les opérateurs arithmétiques.\\
Tu peux virer cette ligne en vrai ; je le ferais pour toi

2020-03-15 13:31 UTC, RaitoBezarius commented on src/main.tex
> +    - $\Sigma^*$ est l'ensemble des mots possibles qu'on peut construire à partir de $\Sigma$.\\
Celle là aussi

2020-03-15 13:49 UTC, Maryem-HAJJI commented on src/main.tex
> +    \item On suppose dans cette partie que:\\ - $\Sigma$ est un alphabet fini qui contient les lettres de l'alphabet latin, les parenthèses et les opérateurs arithmétiques.\\
Aaaa okeyh, merciii

2020-03-15 13:57 UTC, merged