Create Projet_Lean_Ivan.tex
RaitoBezarius/projet-maths-lean pull request #2
Opened 2020-03-13 13:22 UTC by Ivan-Hasenohr

2020-03-14 18:51 UTC, RaitoBezarius requested changes
Sur le fond, ça m'a l'air bien ; juste des écueils dangereux!

2020-03-14 18:51 UTC, RaitoBezarius commented on src/Projet_Lean_Ivan.tex
> +\documentclass[french,frenchkw]{article}
Ce fichier a l'air comme celui d'avant, supprime celui là donc

2020-03-14 18:51 UTC, RaitoBezarius commented on src/Function, Proposition et Advanced Proposition Worlds.tex
> +Ici nous allons présenter 4 techniques fondamentales pour l'utilisation de fonctions, une fonction en Lean étant exactement une fonction mathématique, donc un objet abstrait qui prend en argument un
L'idée c'est quand même plutôt dire, en Lean, il y a des types, un peu comme en informatique.
Un type en mathématiques, c'est un objet abstrait opaque qui se rapproche le plus d'un ensemble.

Après, il y a pas vraiment des fonctions en Lean, ça y ressemble, mais ce sont plutôt des types encore. Le type fonction c'est le type α → β pour α, β deux types quelconques par exemple (modulo les problèmes d'ensembles de tous les ensembles, c.f. https://fr.wikipedia.org/wiki/Univers_(logique))

Et on lit une "fonction Lean" comme `f : α → β` est un type qui prend une preuve de α et produit une preuve de β.
En fait, les fonctions de Lean, ce sont exactement les implications (normal, c'est du calcul de propositions!).

Donc, pour résumé, attention à l'écueil: ensemble A, ensemble B. C'est faux, une fonction Lean prend une preuve de A et donne une preuve de B.
Ici, nous n'avons aucun ensemble, on a même pas de théorie des ensembles.
On peut remarquer que cela est possible, on peut la construire (elle est dans mathlib en tant que le module set).
Mais tout ce qu'on a ce sont des types!

2020-03-14 18:51 UTC, RaitoBezarius commented on src/Function, Proposition et Advanced Proposition Worlds.tex
> +La première de ces tactiques est \textit{exact}. Elle permet de dire à Lean que le but recherché correspond exactement à ce que vous lui indiquez. Par exemple, si le but est un élément de P, et que v
"si le but est un élément de P"
en réalité, c'est plutôt: si le but c'est "il existe un élément de type P", écris le en maths sans hésiter: $\exists p, p \in P$ ou quelque chose comme ça.

2020-03-14 18:51 UTC, RaitoBezarius commented on src/Function, Proposition et Advanced Proposition Worlds.tex
> +Lorsque vous manipulez des fonctions, Lean peut vous demander de créer une fonction d'un ensemble P dans un autre ensemble Q. Une méthode est alors de disposer d'un élément de P à partir duquel vous
Fonctions = implications, donc pars du pdv implications ici et dis que tu dois prouver une implication, donc intro permet d'introduire l'hypothèse de l'implication et reformule le but en le second membre de l'implication.

2020-03-14 18:51 UTC, RaitoBezarius commented on src/Function, Proposition et Advanced Proposition Worlds.tex
> +De façon similaire, \textit{intros} permet d'introduire plusieurs variables/fonctions consécutives.\\
Idem, on peut dire qu'on a p_1 → p_2 → p_3 → p_n → q
On peut faire `intros p_1 p_2 … p_n` et le but devient `q`

2020-03-14 18:51 UTC, RaitoBezarius commented on src/Function, Proposition et Advanced Proposition Worlds.tex
> +Cette technique permet de nommer de nouvelles variables : par exemple, si vous disposez de $p \in P$ et de f : $P \implies Q$, alors \textit{have q : Q := f(p),} vous permet de créer un élément $q =
Mentionne rapidement entre parenthèses principe du Démiurge.

2020-03-14 18:51 UTC, RaitoBezarius commented on src/Function, Proposition et Advanced Proposition Worlds.tex
> +Cette technique permet de nommer de nouvelles variables : par exemple, si vous disposez de $p \in P$ et de f : $P \implies Q$, alors \textit{have q : Q := f(p),} vous permet de créer un élément $q =
Ne met pas des impliques en LaTeX mais des `\to` de fonctions.

2020-03-14 18:51 UTC, RaitoBezarius commented on src/Function, Proposition et Advanced Proposition Worlds.tex
> +Un élément important à remarquer est qu'en Lean, toutes les fonctions sont curryfiées.\\
Fais attention, `f : (p → q) → r` est currifiyée, hein. Mais tu peux pas faire `f p` et obtenir `g : q → r`, tu vois ce que je veux dire?

2020-03-14 18:51 UTC, RaitoBezarius commented on src/Function, Proposition et Advanced Proposition Worlds.tex
> +Un élément important à remarquer est qu'en Lean, toutes les fonctions sont curryfiées.\\
Notamment car `f : (p → q) → r → s`, bah `f pq : r → s` ça marche par exemple.

2020-03-14 18:51 UTC, RaitoBezarius commented on src/Function, Proposition et Advanced Proposition Worlds.tex
> +La manipulation des fonctions ne pose pas de difficultés particulières, une fois maîtrisées les techniques de base que sont exact, intro, have et apply.\\
Tralalala, cette ligne n'apporte rien

2020-03-14 18:51 UTC, RaitoBezarius commented on src/Function, Proposition et Advanced Proposition Worlds.tex
> +Voici un exemple de niveau de ce monde, le niveau 6, qui demande de créer une fonction de fonctions assez complexe, et qui utilise le fait que ces fonctions sont curryfiées. \\
Plutôt fastidieuse que complexe

2020-03-14 18:51 UTC, RaitoBezarius commented on src/Function, Proposition et Advanced Proposition Worlds.tex
> +\textit{exact g(p),} -- On trouve le résultat demandé \\
Tu n'as pas besoin de parenthèses dans `exact g(p)`, ça marche `exact (g p)` par exemple.

2020-03-14 18:51 UTC, RaitoBezarius commented on src/Function, Proposition et Advanced Proposition Worlds.tex
> +\textit{exact g(p),} -- On trouve le résultat demandé \\
Mieux: `exact g p` je crois.

2020-03-14 18:51 UTC, RaitoBezarius commented on src/Function, Proposition et Advanced Proposition Worlds.tex
> +$(P Q R : Type) : (P \implies (Q \implies R)) \implies ((P \implies Q) \implies (P \implies R))$\\
Même remarques sur les \implies → \to

2020-03-14 18:51 UTC, RaitoBezarius commented on src/Function, Proposition et Advanced Proposition Worlds.tex
> +Dans ce monde on aborde un aspect fondamental de l'assistant de preuves Lean : comment modélise-t-on une preuve ? Qu'est-ce qu'une preuve ? Lean le modélise comme ceci : Si l'on prend une proposition
Faut faire attention, dans Lean, tu as `Prop` qui est un type de proposition dont on connaît pas obligatoirement leur valeur.
Puis, tu as des types qui prouvent des trucs.

Je peux écrire: `def absurd {P: Type*}: Prop := P & (¬P)` je définis l'absurdité comme étant une preuve de P et non(P). pour un type P quelconque (d'univers arbitraire c'est ça l'étoile. Mais on s'en fout.)

Mais en même temps, quand j'écris `theorem absurd_is_equivalent_to_everything {P: Type*} {Q: Type*} absurd P → Q := sorry`, je démontre que si on me donne l'absurdité sur la proposition P (i.e. P et non(P)), alors je peux prouver Q pour n'importe quel Q.

Donc dans l'idée, une preuve c'est la *construction* d'un type avec d'autres types.
« L'ensemble des preuves qui la prouve », attention, attention. Cet ensemble existe-t-il ?
Est-ce que ça a du sens ?

Soit F(T) = { P | P prouve T }, pour T une proposition logique. F existe-t-il vraiment ?
Faut faire attention, une proposition c'est juste un assemblage de symboles logiques qui ont un sens selon les axiomes en vigueur.

La preuve d'une proposition c'est la construction d'un type à partir d'autres types.

La valeur de vérité d'une proposition c'est pas toujours défini, e.g. en logique classique, tiers exclu dit: oui soit P est vrai soit P ne l'est pas.
En logique intuitionniste, aucune réponse, l'écho sonne creux. Les propositions peuvent avoir ≥ 3 valeurs de « vérité » (vérité encore?) possibles.

2020-03-14 18:51 UTC, RaitoBezarius commented on src/Function, Proposition et Advanced Proposition Worlds.tex
> +C'est ici que les fonctions prennent toute leur importance : pour montrer qu'une proposition A entraîne une autre proposition B, il suffit de montrer qu'à partir d'un élément de A on peut créer un él
Pour montrer que A implique B, il suffit de construire le type A → B :-). Phrase en une ligne!
Tu peux élaborer, en effet: le type A → B c'est exactement le type de l'implication car pour produire une preuve de B, il faut une preuve de A.

2020-03-14 18:51 UTC, RaitoBezarius commented on src/Function, Proposition et Advanced Proposition Worlds.tex
> +En Lean, on demande donc de créer un élément de l'ensemble des preuves du Lemme, soit créer une fonction qui va de l'ensemble des preuves que $P \implies Q$ vers l'ensemble des preuves que $\lnot Q \
À nouveau, attention à l'ensemble des preuves. Nous ne sommes pas en théorie des ensembles.
Lean demande de construire un type, i.e. construire la preuve.
Je n'ai jamais parlé d'ensemble, ça n'existe pas dans le Vrai Monde ™ !

2020-03-14 18:51 UTC, RaitoBezarius commented on src/Function, Proposition et Advanced Proposition Worlds.tex
> +Dans ce monde on démontre à l'aide de fonctions et de nouvelles méthodes les règles de base de la manipulation d'intersection et d'union de propositions. Un exemple combinant la plupart des nouvelles
Intersection/union c'est compliqué
Faut parler de conjonction/disjonction logique plutôt à mon sens

2020-03-15 00:44 UTC, RaitoBezarius requested changes
Encore deux trois trucs et on y est

2020-03-15 00:44 UTC, RaitoBezarius commented on src/Advanced addition, mutiplication et inequality world.tex
> +Lorsque vous manipulez des fonctions, Lean peut vous demander de créer une fonction d'un type P vers un type Q. Une méthode est alors de d'émettre l'hypothèse qu'on dispose d'un $p\in P$ à partir duq
Fais attention, `p \in P` ça veut dire: p est dans l'ensemble|chose P tandis que `p: P` c'est `p` est de type`P`, ce n'est pas la même chose hélas

Donc, parle plutôt de `p: P` que de `p \in P` en expliquant que ça a un sens similaire mais que nous ne sommes pas en théorie des ensembles donc `p \in P` est plus proche du monde ensembliste que `p: P`, tu n'écris pas `p \in (\forall x \in X, x = 0)` par exemple. Pourtant, c'est un peu ce qu'on fait (et ce que tu écris).

2020-03-15 00:44 UTC, RaitoBezarius commented on src/Advanced addition, mutiplication et inequality world.tex
> +Cette technique permet de nommer de nouvelles variables : par exemple, si vous disposez de $p \in P$ et de f : $P \to Q$, alors \textit{have q : Q := f(p),} vous permet de créer un élément $q = f(p)$
Nommer, renommer c'est un autre pouvoir dans le game :paintbrush:

2020-03-15 00:44 UTC, RaitoBezarius commented on src/Advanced addition, mutiplication et inequality world.tex
> +Ce qui se résout tout aussi trivialement : \textit{exact h(p),}.\\
pas de trivial ; rien n'est trivial
il se résoud succintement si tu veux

2020-03-15 00:44 UTC, RaitoBezarius commented on src/Advanced addition, mutiplication et inequality world.tex
> +\textbf{Lemme} : ($P \to Q) \to (\lnot Q \to \lnot Q)$. \\
vraiment ¬Q → ¬Q ? ou ¬Q → ¬P (auquel cas, parle du fait qu'il s'agit exactement de la contraposée.)

2020-03-15 00:44 UTC, RaitoBezarius commented on src/Advanced addition, mutiplication et inequality world.tex
> +L'astuce est ensuite de revenir à la définition de $\lnot P$ : $\lnot P$ ssi $P \to false$. On retranscrit cette définition : \\
écris: `$\lnot P \equiv P \to false`, c'est plus joli et clair. N'utilise pas ssi, ça n'a pas de vrai définition.

Plutôt, ¬P est définitionnellement égal à P → false.

2020-03-15 00:44 UTC, RaitoBezarius commented on src/Advanced addition, mutiplication et inequality world.tex
> +L'astuce est ensuite de revenir à la définition de $\lnot P$ : $\lnot P$ ssi $P \to false$. On retranscrit cette définition : \\
(mais aussi équivalent à P → false logiquement.)

2020-03-15 00:44 UTC, RaitoBezarius commented on src/Advanced addition, mutiplication et inequality world.tex
> +Le but est alors réécrit en $(Q \to false) \to P \to false$, ce qui revient à créer une fonction curryfiée des éléments de type $(Q \to false) \times P$ vers les preuves de $false$\\
Te manque une parenthèse je pense (P → false)

2020-03-15 11:59 UTC, Ivan-Hasenohr commented on src/Advanced addition, mutiplication et inequality world.tex
> +Le but est alors réécrit en $(Q \to false) \to P \to false$, ce qui revient à créer une fonction curryfiée des éléments de type $(Q \to false) \times P$ vers les preuves de $false$\\
Nope j'ai vérifié sur le natural game

2020-03-15 12:00 UTC, RaitoBezarius commented on src/Advanced addition, mutiplication et inequality world.tex
> +Le but est alors réécrit en $(Q \to false) \to P \to false$, ce qui revient à créer une fonction curryfiée des éléments de type $(Q \to false) \times P$ vers les preuves de $false$\\
Okay

2020-03-15 13:34 UTC, RaitoBezarius approved these changes
Sounds good modulo typo

2020-03-15 13:34 UTC, RaitoBezarius commented on src/Function, Proposition et Advanced Proposition Worlds.tex
> +En Lean, on demande donc de créer une fonction qui prend une preuve que $P \to Q$ et renvoie une preuve de $\lnot Q \to \lnot Q$.
Typo: `\lnot P` ici

2020-03-15 13:34 UTC, RaitoBezarius commented on src/Function, Proposition et Advanced Proposition Worlds.tex
> +Lean nous demande alors de créer un élément de type $\lnot Q \to \lnot Q$, qui serait l'image de la fonction qu'il nous est demandé de créer.\\
`\lnot P` typoe

2020-03-15 13:59 UTC, merged